// const express = require("express");
// const router = express.Router();
// const multer  = require('multer');



// // Multer configuration
// const storage = multer.diskStorage({
//   destination: function (req, file, cb) {
//     cb(null, 'uploads/')
//   },
//   filename: function (req, file, cb) {
//     cb(null, file.fieldname + '-' + Date.now() + path.extname(file.originalname))
//   }
// });
// const upload = multer({ storage: storage });

// // Serve the HTML file
// router.get('/', (req, res) => {
//   res.sendFile(path.join(__dirname, 'upload.html'));
// });

// // Handle file upload
// router.post('/upload', upload.single('file'), (req, res) => {
//   res.send('File uploaded successfully');
// });

const express = require('express');
const multer = require('multer');
const path = require('path');
const fs = require('fs');

const app = express();
const port = 4000;

const Toys = require("../models/storeModel")

// Set up middleware for parsing form data and handling file uploads
const upload = multer({ dest: 'uploads/' });

// Serve static files from the 'public' directory
app.use(express.static('public'));

// Define a route to render the doll collection page
router.get('/addDoll', async(req, res) => {
  try {
    let toys = await Toys.find()
    res.render("renderToys", {toys:toys});
  } catch (error) {
    res.status(400).send("cant find toys")
  }
  
});

// Define a route to handle form submission for adding a new doll
router.post('/addDoll', upload.single('image'), (req, res) => {
  
  const toys  = new Toys(req.body)
  const image = req.file.filename; // The filename generated by multer for the uploaded image

  // Save the doll information to your database

  // Redirect back to the doll collection page after adding the doll
  res.redirect('/');
});

app.listen(port, () => {
  console.log(`Server is running on http://localhost:${port}`);
});
